server:
  port: ${SERVER_PORT}

spring:
  application.name: employee-serv
  profiles.active: h2
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  messages:
    basename: error_messages.properties
